default:
	lessc mask.less -o mask.css
	lessc index.less -o index.css
	lessc plan.less -o plan.css
	lessc about.less -o about.css
	lessc qa.less -o qa.css
	lessc req.less -o req.css
	lessc as.less -o as.css
